### ISSUE TITLE
郵便番号が設定されてる高層ビルがある件

### ISSUE THREAD

**Issue by kouyaf77** [rinkei/jipcode#11]
通りすがりですいません。

高層ビル(階ごと)に郵便番号が振られるケースがあるのですが、フラグを立てるもしくは、buildingのようなキーにビル名が入るといいなと思いました。

たしか、日本郵政のCSVがビルのフラグ等を持っていなかったような気がするので、実現するのは難しいかも知れません。

```rb
require 'jipcode'

puts Jipcode.locate('1066090')
# => {:zipcode=>"1066090", :prefecture=>"東京都", :city=>"港区", :town=>"六本木泉ガーデンタワー"}
```

**Comment by rinkei** [comment]
提案ありがとうございます。
jipcodeは住所入力フォームの補完を開発しやすくすることが目的としています。
自分はビルであることを示す必要があるフォームはあまり見たことがないので、ご提案のフラグについても今回は見送りたいと思います。
